-- audit.run: one row per framework execution, across all workspaces.
-- run_id is generated by the caller (pipeline expression or
-- notebooks/bronze/run_manager.new_run_id) in the form yyyyMMdd-HHmmss-XXXXXX
-- so it can be threaded through landing paths, Bronze technical columns and
-- child audit rows before any insert happens.
CREATE TABLE [audit].[run]
(
    run_id              VARCHAR(64)    NOT NULL CONSTRAINT pk_run PRIMARY KEY CLUSTERED,
    framework_name      VARCHAR(100)   NOT NULL,
    environment         VARCHAR(10)    NOT NULL,
    workspace_id        VARCHAR(64)    NULL,
    workspace_name      NVARCHAR(256)  NULL,
    pipeline_name       NVARCHAR(256)  NULL,
    pipeline_run_id     VARCHAR(64)    NULL,
    notebook_name       NVARCHAR(256)  NULL,
    trigger_type        VARCHAR(30)    NULL,   -- SCHEDULED | MANUAL | EVENT | REPLAY
    trigger_name        NVARCHAR(256)  NULL,
    initiated_by        NVARCHAR(256)  NULL,
    run_timestamp       CHAR(14)       NULL,   -- yyyyMMddHHmmss, used in landing file names
    entity_group        VARCHAR(100)   NULL,
    start_datetime      DATETIME2(3)   NOT NULL CONSTRAINT df_run_start DEFAULT SYSUTCDATETIME(),
    end_datetime        DATETIME2(3)   NULL,
    status              VARCHAR(20)    NOT NULL,
    total_entities      INT            NULL,
    successful_entities INT            NULL,
    failed_entities     INT            NULL,
    skipped_entities    INT            NULL,
    message             NVARCHAR(4000) NULL,
    created_datetime    DATETIME2(3)   NOT NULL CONSTRAINT df_run_created DEFAULT SYSUTCDATETIME(),
    updated_datetime    DATETIME2(3)   NULL,
    CONSTRAINT ck_run_status CHECK (status IN ('STARTED', 'RUNNING', 'SUCCEEDED', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED'))
);
