"""Validation Engine: metadata-driven data-quality rules (spec section 50).

Rules come from control.validation_rule plus built-in defaults that every
entity gets unless it overrides the same rule_type:

  PRIMARY_KEY_NULL        FAIL  (entities with a primary key)
  DUPLICATE_PRIMARY_KEY   WARN  (deduplication resolves duplicates; the
                                 warning keeps them visible in audit)
  COLUMN_MISSING          FAIL
  DATA_TYPE_MISMATCH      FAIL  (every non-STRING column; see below)

Type checks run against the RAW staging rows (source-shaped, before the
projection casts to target types). Spark's default non-ANSI CAST turns an
unconvertible value into NULL silently; checking the already-cast frame
could never see it. A value fails when the raw source value is NOT NULL but
its conversion (try_cast, or the column_mapping expression) is NULL.

Supported rule types:
  PRIMARY_KEY_NULL, DUPLICATE_PRIMARY_KEY, MANDATORY_COLUMN_NULL,
  COLUMN_MISSING (schema check), DATA_TYPE_MISMATCH (try_cast),
  WATERMARK_INVALID (NULL, or older than the stored watermark on an
  incremental load), ROW_COUNT_ANOMALY (vs the previous run's count,
  threshold from load_configuration), CUSTOM (Spark SQL predicate every row
  must satisfy).

Failure actions: FAIL (fails the entity when fail_on_validation_error is
on), WARN (recorded, processing continues), IGNORE (evaluated and recorded
as IGNORED, never affects the outcome).

SQL is generated by pure functions over a temp view name, so it is unit
tested without Spark. Results carry counts only -- never row values.
"""

from dataclasses import dataclass
from typing import Iterable, List, Optional, Sequence

from notebooks.bronze.models import (
    ACTION_FAIL,
    ACTION_IGNORE,
    ACTION_WARN,
    STAGE_POST,
    STAGE_PRE,
    WATERMARK_DATETIME,
    WATERMARK_NUMERIC,
    EntityConfig,
    ValidationRule,
)
from notebooks.bronze.schema_manager import quote

PRIMARY_KEY_NULL = "PRIMARY_KEY_NULL"
DUPLICATE_PRIMARY_KEY = "DUPLICATE_PRIMARY_KEY"
MANDATORY_COLUMN_NULL = "MANDATORY_COLUMN_NULL"
COLUMN_MISSING = "COLUMN_MISSING"
DATA_TYPE_MISMATCH = "DATA_TYPE_MISMATCH"
WATERMARK_INVALID = "WATERMARK_INVALID"
ROW_COUNT_ANOMALY = "ROW_COUNT_ANOMALY"
CUSTOM = "CUSTOM"

STATUS_PASSED = "PASSED"
STATUS_FAILED = "FAILED"
STATUS_WARNING = "WARNING"
STATUS_IGNORED = "IGNORED"


@dataclass(frozen=True)
class ValidationResult:
    rule_id: Optional[int]
    rule_name: str
    rule_type: str
    stage: str
    status: str
    failure_action: str
    severity: str
    failed_row_count: Optional[int] = None
    expected_value: Optional[str] = None
    actual_value: Optional[str] = None
    error_message: Optional[str] = None

    @property
    def is_blocking(self) -> bool:
        return self.status == STATUS_FAILED


def builtin_rules(entity: EntityConfig) -> List[ValidationRule]:
    rules = [ValidationRule(None, "builtin_column_missing", COLUMN_MISSING, severity="CRITICAL",
                            failure_action=ACTION_FAIL, stage=STAGE_PRE)]
    if typed_columns(entity):
        rules.append(ValidationRule(None, "builtin_data_type_mismatch", DATA_TYPE_MISMATCH, severity="HIGH",
                                    failure_action=ACTION_FAIL, stage=STAGE_PRE))
    if entity.primary_key:
        rules += [
            ValidationRule(None, "builtin_primary_key_null", PRIMARY_KEY_NULL, severity="CRITICAL",
                           failure_action=ACTION_FAIL, stage=STAGE_PRE),
            ValidationRule(None, "builtin_duplicate_primary_key", DUPLICATE_PRIMARY_KEY, severity="MEDIUM",
                           failure_action=ACTION_WARN, stage=STAGE_PRE),
        ]
    return rules


def typed_columns(entity: EntityConfig):
    return [c for c in entity.ordered_columns if c.target_data_type.split("(")[0].strip().upper() != "STRING"]


def build_type_check_condition(column) -> str:
    """Row-level predicate: raw value present but not convertible."""
    source = quote(column.source_column)
    if column.source_expression:
        converted = f"CAST(({column.source_expression}) AS {column.target_data_type})"
    else:
        converted = f"try_cast(CAST({source} AS STRING) AS {column.target_data_type})"
    return f"({source} IS NOT NULL AND {converted} IS NULL)"


def effective_rules(entity: EntityConfig, stage: str) -> List[ValidationRule]:
    """Metadata rules for the stage, plus built-ins whose rule_type the
    entity has not overridden. A column-specific DATA_TYPE_MISMATCH rule does
    NOT disable the all-columns built-in (it only adds its own action)."""
    configured = [r for r in entity.validation_rules if r.stage == stage]
    overridden = {r.rule_type for r in entity.validation_rules
                  if not (r.rule_type == DATA_TYPE_MISMATCH and r.column_name)}
    builtins = [r for r in builtin_rules(entity) if r.stage == stage and r.rule_type not in overridden]
    return builtins + configured


def _pk_columns(entity: EntityConfig) -> List[str]:
    return [quote(c) for c in entity.primary_key]


def build_rule_sql(rule: ValidationRule, entity: EntityConfig, view: str,
                   previous_watermark: Optional[str] = None, raw_view: Optional[str] = None) -> Optional[str]:
    """SQL returning one row with column failed_row_count, or None for rules
    evaluated outside SQL (COLUMN_MISSING, ROW_COUNT_ANOMALY). view holds the
    projected (target-typed) rows; raw_view the source-shaped staging rows
    used by DATA_TYPE_MISMATCH (defaults to view)."""
    rule_type = rule.rule_type
    if rule_type == PRIMARY_KEY_NULL:
        if not entity.primary_key:
            return None
        predicate = " OR ".join(f"{c} IS NULL" for c in _pk_columns(entity))
        return f"SELECT COUNT(*) AS failed_row_count FROM {view} WHERE {predicate}"
    if rule_type == DUPLICATE_PRIMARY_KEY:
        if not entity.primary_key:
            return None
        keys = ", ".join(_pk_columns(entity))
        return (f"SELECT COALESCE(SUM(n - 1), 0) AS failed_row_count FROM "
                f"(SELECT COUNT(*) AS n FROM {view} GROUP BY {keys} HAVING COUNT(*) > 1) AS d")
    if rule_type == MANDATORY_COLUMN_NULL:
        return f"SELECT COUNT(*) AS failed_row_count FROM {view} WHERE {quote(rule.column_name)} IS NULL"
    if rule_type == DATA_TYPE_MISMATCH:
        if rule.column_name:
            column = entity.column(rule.column_name)
            if column is None:
                raise ValueError(f"DATA_TYPE_MISMATCH rule {rule.rule_name!r}: unknown column {rule.column_name!r}")
            columns = [column]
        else:
            columns = typed_columns(entity)
        if not columns:
            return None
        predicate = " OR ".join(build_type_check_condition(c) for c in columns)
        return f"SELECT COUNT(*) AS failed_row_count FROM {raw_view or view} WHERE {predicate}"
    if rule_type == WATERMARK_INVALID:
        column_name = rule.column_name or entity.watermark_target_column
        col = quote(column_name)
        condition = f"{col} IS NULL"
        if previous_watermark is not None and entity.is_incremental:
            if entity.watermark_type == WATERMARK_NUMERIC:
                literal = str(float(previous_watermark)) if "." in previous_watermark else str(int(previous_watermark))
            elif entity.watermark_type == WATERMARK_DATETIME:
                literal = f"CAST('{previous_watermark}' AS TIMESTAMP)"
            else:
                literal = "'" + previous_watermark.replace("'", "\\'") + "'"
            condition += f" OR {col} < {literal}"
        return f"SELECT COUNT(*) AS failed_row_count FROM {view} WHERE {condition}"
    if rule_type == CUSTOM:
        if not rule.expression:
            raise ValueError(f"CUSTOM validation rule {rule.rule_name!r} has no expression")
        return f"SELECT COUNT(*) AS failed_row_count FROM {view} WHERE NOT ({rule.expression})"
    if rule_type in (COLUMN_MISSING, ROW_COUNT_ANOMALY):
        return None
    raise ValueError(f"Unknown validation rule_type {rule_type!r} ({rule.rule_name})")


def missing_columns(entity: EntityConfig, present_columns: Iterable[str]) -> List[str]:
    """Source columns absent from staging (staging is source-shaped)."""
    present = {c.lower() for c in present_columns}
    return [c.source_column for c in entity.ordered_columns if c.source_column.lower() not in present]


def row_count_anomaly(current: int, previous: Optional[int], threshold_pct: Optional[float]) -> Optional[float]:
    """Percentage change vs previous, or None when not evaluable. An anomaly
    is flagged by the caller when abs(change) > threshold_pct."""
    if previous is None or threshold_pct is None:
        return None
    if previous == 0:
        return 0.0 if current == 0 else 100.0
    return (current - previous) * 100.0 / previous


def to_result(rule: ValidationRule, failed: bool, failed_row_count: Optional[int] = None,
              expected: Optional[str] = None, actual: Optional[str] = None,
              message: Optional[str] = None) -> ValidationResult:
    if rule.failure_action == ACTION_IGNORE:
        status = STATUS_IGNORED if failed else STATUS_PASSED
    elif not failed:
        status = STATUS_PASSED
    elif rule.failure_action == ACTION_WARN:
        status = STATUS_WARNING
    else:
        status = STATUS_FAILED
    return ValidationResult(
        rule_id=rule.rule_id,
        rule_name=rule.rule_name,
        rule_type=rule.rule_type,
        stage=rule.stage,
        status=status,
        failure_action=rule.failure_action,
        severity=rule.severity,
        failed_row_count=failed_row_count,
        expected_value=expected,
        actual_value=actual,
        error_message=message if failed else None,
    )


def blocking_failures(results: Sequence[ValidationResult], fail_on_validation_error: bool) -> List[ValidationResult]:
    if not fail_on_validation_error:
        return []
    return [r for r in results if r.is_blocking]


class ValidationEngine:
    """Spark adapter: evaluates the stage's rules against a DataFrame."""

    def __init__(self, spark):
        self.spark = spark

    def run(self, df, entity: EntityConfig, stage: str, view_suffix: str,
            previous_watermark: Optional[str] = None, previous_row_count: Optional[int] = None,
            current_row_count: Optional[int] = None, raw_df=None) -> List[ValidationResult]:
        """df: projected (target-typed) rows. raw_df: the source-shaped
        staging rows of this run, for COLUMN_MISSING and DATA_TYPE_MISMATCH
        (PRE stage). Stateless -- safe to share across entity threads."""
        base = f"_bronze_validate_{entity.entity_id}_{stage.lower()}_{view_suffix}".replace("-", "_")
        view = base
        raw_view = f"{base}_raw" if raw_df is not None else None
        df.createOrReplaceTempView(view)
        if raw_df is not None:
            raw_df.createOrReplaceTempView(raw_view)
        if raw_df is not None:
            present = list(raw_df.columns)
        else:
            present = [c.source_column for c in entity.ordered_columns if c.target_column in df.columns]
        results: List[ValidationResult] = []
        try:
            for rule in effective_rules(entity, stage):
                results.append(self._evaluate(rule, df, entity, view, raw_view, present, previous_watermark,
                                              previous_row_count, current_row_count))
        finally:
            self.spark.catalog.dropTempView(view)
            if raw_view:
                self.spark.catalog.dropTempView(raw_view)
        return results

    def _evaluate(self, rule, df, entity, view, raw_view, present, previous_watermark, previous_row_count,
                  current_row_count):
        if rule.rule_type == COLUMN_MISSING:
            missing = missing_columns(entity, present)
            return to_result(rule, bool(missing), len(missing), "0", str(len(missing)),
                             f"missing column(s): {', '.join(missing)}" if missing else None)
        if rule.rule_type == ROW_COUNT_ANOMALY:
            current = current_row_count if current_row_count is not None else df.count()
            change = row_count_anomaly(current, previous_row_count, entity.load_config.row_count_anomaly_threshold_pct)
            threshold = entity.load_config.row_count_anomaly_threshold_pct
            failed = change is not None and abs(change) > threshold
            return to_result(rule, failed, None,
                             None if threshold is None else f"<= {threshold}% change",
                             None if change is None else f"{change:.2f}%",
                             f"row count changed {change:.2f}% vs previous run ({previous_row_count} -> {current})"
                             if failed else None)
        if rule.rule_type == DATA_TYPE_MISMATCH and missing_columns(entity, present):
            # a missing column is reported by COLUMN_MISSING; its type cannot be checked
            return to_result(rule, False, 0, "0", "0")
        sql = build_rule_sql(rule, entity, view, previous_watermark, raw_view)
        if sql is None:
            return to_result(rule, False, 0, "0", "0")
        failed_rows = int(self.spark.sql(sql).collect()[0]["failed_row_count"] or 0)
        return to_result(rule, failed_rows > 0, failed_rows, "0", str(failed_rows),
                         f"{failed_rows} row(s) violate {rule.rule_type}"
                         + (f" on {rule.column_name}" if rule.column_name else ""))
